using System;
using System.Collections.Generic;
using System.Text;

namespace ArkSaveEditor.Entities.LowLevel.AutoGeneratedClasses
{
    /// <summary>
    /// Defines data for built in maps.
    /// </summary>
    public static class ArkMapDataTable
    {
        public static Dictionary<string, ArkMapData> arkmaps = new Dictionary<string, ArkMapData>
        {
            ////////
            { "Extinction", new ArkMapData
                {
                    displayName = "Extinction",
                    isOfficial = true,
                    backgroundColor = null,
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    pixelsPerMeter = 1.94f,
                    sourceImageSize = 15700
                }
            },
            ///////
            { "TheCenter", new ArkMapData
                {
                    displayName = "The Center",
                    isOfficial = true,
                    backgroundColor = "#0070C1",
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    pixelsPerMeter = 3f,
                    sourceImageSize = 33650, //Original image
                    mapImageOffset = new Vector2(0, -18411*10)
                }
            }
            ///////
        };
    }
}
