using System;
using System.Collections.Generic;
using System.Text;

namespace ArkSaveEditor.Entities.LowLevel.AutoGeneratedClasses
{
    /// <summary>
    /// Defines data for built in maps.
    /// </summary>
    public static class ArkMapDataTable
    {
        public static Dictionary<string, ArkMapData> arkmaps = new Dictionary<string, ArkMapData>
        {
            ////////
            { "Extinction", new ArkMapData
                {
                    displayName = "Extinction",
                    isOfficial = true,
                    isTheCenter = false,
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    transformOffsets = new WorldTransformOffsets
                    {
                        sizeMult = 0.765f,
                        offsetX = 0.040f,
                        offsetY = 0.0608f /* Higher values move map down */
                    }
                }
            },
            ///////
            { "TheCenter", new ArkMapData
                {
                    displayName = "The Center",
                    isOfficial = true,
                    isTheCenter = true,
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    transformOffsets = new WorldTransformOffsets
                    {
                        sizeMult = 0.765f,
                        offsetX = 0.040f,
                        offsetY = 0.0608f /* Higher values move map down */
                    }
                }
            }
        };
    }
}
